OpenAIModel:
  model: "gpt-4o-mini"
  api_key: ""
  base_url: "https://api.openai.com/v1/"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"
  language: "Chinese"